--------------------------------------------------------
--  File created - суббота-сентября-29-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "EMPLOYEE" 
   (	"ID" NUMBER, 
	"DEPARTMENT_ID" NUMBER, 
	"CHIEF_ID" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
	"SALARY" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYS.EMPLOYEE
SET DEFINE OFF;
Insert into EMPLOYEE (ID,DEPARTMENT_ID,CHIEF_ID,NAME,SALARY) values ('1','1','1','А.Долюк','150000');
Insert into EMPLOYEE (ID,DEPARTMENT_ID,CHIEF_ID,NAME,SALARY) values ('2','2','2','А.Сорокин','160000');
Insert into EMPLOYEE (ID,DEPARTMENT_ID,CHIEF_ID,NAME,SALARY) values ('3','3','3','В.','150000');
Insert into EMPLOYEE (ID,DEPARTMENT_ID,CHIEF_ID,NAME,SALARY) values ('4','4','4','В.Валуев','140000');
Insert into EMPLOYEE (ID,DEPARTMENT_ID,CHIEF_ID,NAME,SALARY) values ('5','4','4','А','150000');
--------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."EMPLOYEE_PK" ON "SYS"."EMPLOYEE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "SYS"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."EMPLOYEE" MODIFY ("ID" NOT NULL ENABLE);
